### ISSUE TITLE
Questions about the GCOND-X

### ISSUE THREAD

**Issue by jiaweiz716** [ChandlerBang/GCond#15]
Hi,

Thanks for the great work!

In the function test_with_val, it can be seen that:
```
if self.args.lr_adj == 0:
    n = len(labels_syn)
    adj_syn = torch.zeros((n, n))
```

Howerver, if only set the self.args.lr_adj == 0, in the code of function train, we notice that:
```
for ol in range(outer_loop):
     adj_syn = pge(self.feat_syn)
     adj_syn_norm = utils.normalize_adj_tensor(adj_syn, sparse=False)
     feat_syn_norm = feat_syn
```
the used adj_syn is not the identity matrix. In other words, the process of training include the structure of the graph.

_**So, my question is how to set it up to get result GCOND-X?**_ 

Only set self.args.lr_adj == 0 or set self.args.lr_adj == 0 & adj_syn = identity matrix?

**Comment by ChandlerBang** [comment]
Thanks for your interest in our work. We recommend you try our newly released package [[GraphSlim]](https://github.com/Emory-Melody/GraphSlim)

The code for GCondX is [here](https://github.com/Emory-Melody/GraphSlim/blob/main/graphslim/condensation/gcondx.py) and the scripts for benchmarking can be found [here](https://github.com/Emory-Melody/GraphSlim/tree/main/benchmark). Feel free to let us know if you have further questions.

**Comment by jiaweiz716** [comment]
Ok, thanks!
