### ISSUE TITLE
missing file train_cond_tranduct_sampler.py

### ISSUE THREAD

**Issue by agoyang** [ChandlerBang/GCond#2]
In scripts/run_main.sh, there is a line:
`python train_cond_tranduct_sampler.py --dataset ogbn-arxiv --mlp=0 --nlayers=2 --sgc=1 --lr_feat=0.01 --gpu_id=3  --lr_adj=0.01 --r=${r}  --seed=1 --inner=3  --epochs=1000  --save=0`

But it seems like the python file train_cond_tranduct_sampler.py is not in this repository. I've tried to use train_gcond_transduct.py instead, but the argument 'mlp' is not in it.

 Could you provide this file or some information on the argument 'mlp'? It would really help me out. :)

**Comment by ChandlerBang** [comment]
Hey!  Just using `python train_cond_tranduct.py --dataset ogbn-arxiv --nlayers=2 --sgc=1 --lr_feat=0.01 --gpu_id=3 --lr_adj=0.01 --r=${r} --seed=1 --inner=3 --epochs=1000 --save=0` would be good.  I have updated the code just now.

**Comment by agoyang** [comment]
Thank you for your help!
