### ISSUE TITLE
Confused about DC-Graph and GCOND-X

### ISSUE THREAD

**Issue by zhyliu00** [ChandlerBang/GCond#5]
Hi!

This work is inspiring! 
But I'm confused about the DC-Graph and GCOND-X. Since the origin paper says

> As vanilla DC cannot leverage any structure information, we develop a variant named DC-Graph, which additionally leverages graph structure during test stage, to replace DC for the following experiments

> Since DC-Graph and GCONDX do not produce any structure, we simply use an identity matrix as the adjacency matrix when training GNNs solely on condensed features. However, during inference, we use the full graph (transductive setting) or test graph (inductive setting) to propagate information based on the trained GNNS.

The whole pipelines of DC-Graph and GCOND-X should be the same. Namely, they only update $X'$ during training, i.e., replace $A'$ with $I$ in equation (5). So, my confused part is :

1. What is the difference between DC-Graph and GCOND-X?
2. What is the *Condensation* row in Table 1 mean? Why is DC-Grpah and GCOND-X different in *Condensation*?
3. DC-Graph and GCOND-X do not use adjacency matrix $A$ during training, so is the trained GCN  essentially a MLP?

Thanks!

**Comment by ChandlerBang** [comment]
Hi, thank you for your interest in our work.

I can first clarify the second questions:
> Q:  Meaning of the Condensation row in Table 1  & difference between DC-Graph and GCOND-X?

A: The condensation row in Table 1 indicates the information used during condensation. That is to say, DC-Graph only uses node features during training while GCond-X leverages both node features and adjacency matrix. Both DC-graph and GCond-X output synthetic node features to train MLPs. In addition, GCond-X involves graph sampling process as GCond-X needs to deal with the graph structure information during condensation.

> Q: DC-Graph and GCOND-X do not use adjacency matrix during training, so is the trained GCN essentially a MLP?

A: The trained GCN is essentially a MLP. But during test, we will leverages the test adjacency matrix and it becomes a GCN again.

**Comment by zhyliu00** [comment]
Thanks for your reply!
