### ISSUE TITLE
How to get "whole dataset" column from table 2

### ISSUE THREAD

**Issue by LorenzoStigliano** [ChandlerBang/GCond#6]
Hi there I am currently in the process of writing my dissertation and I am trying to replicate your results.

I have a question: how do you calculate the final column on table 2, what model are you training? From my understanding it is simply a 2 layer GCN with 256 hidden units, trained using all the data? Is this correct?

Thank you in advance!
![Screenshot 2023-04-20 at 12 30 23](https://user-images.githubusercontent.com/44544923/233353209-9a8c7256-b1ce-46d7-9af2-79c3efd45ed6.png)

**Comment by ChandlerBang** [comment]
Hi, thank you for your interest in our work. Your understanding is correct.
>  From my understanding it is simply a 2 layer GCN with 256 hidden units, trained using all the data? Is this correct?

In the README file, I have provided the scripts for obtaining the whole dataset performance.

![image](https://user-images.githubusercontent.com/32392709/233445283-2cf0a39e-e35c-430f-a245-5d45155d5b94.png)

There is a similar thread discussing this question. See https://github.com/ChandlerBang/GCond/issues/4.

**Comment by LorenzoStigliano** [comment]
Hi thank you for getting back to me.

Could you help me understand why we need the model on the whole dataset when we do coreset selection?

**Comment by ChandlerBang** [comment]
Hi, the coreset methods require to calculate the cluster center. 

> The Herding method, which is often used in continual learning, picks samples that are closest to the cluster center. K-Center selects the center samples to minimize the largest distance between a sample and its nearest center. 

Here we calculate the cluster center based on the node representations and the node representations are obtained from supervised training.

**Comment by LorenzoStigliano** [comment]
Thank you so much for the clarification!
