### ISSUE TITLE
Code for running the random, herding, k-center baselines

### ISSUE THREAD

**Issue by GooLiang** [ChandlerBang/GCond#9]
Hi! thanks for your awesome work.
I am trying to reproduce the results of random, herding, k-center baseline results in the paper.
As mentioned in the paper, using the implementation provided by "DATASET CONDENSATION WITH GRADIENT MATCHING" for Herding, K-Center, and DC.
However, "DATASET CONDENSATION WITH GRADIENT MATCHING"'s code also does not provide source code implementation.
Could you share the source code used to run the random, herding, k-center algorithm?

**Comment by ChandlerBang** [comment]
Hi we have provided the code for these in train_coreset.py.  
![IMG_4385](https://github.com/ChandlerBang/GCond/assets/32392709/71b1b9ae-ed8c-42f7-80e4-ff6f0bce435c)

**Comment by GooLiang** [comment]
Appreciate for your help!

**Comment by GooLiang** [comment]
Hello author, can you provide the source code of DC-Graph?

**Comment by ChandlerBang** [comment]
You can make simple adjustment on GCond to get DC-Graph:
1. replace the adjacency matrix `A` of the original with a zero matrix (which removes all the existing edges). 
2. fix the condensed adjacency matrix `A'` to an identity matrix.
